spring:
  datasource:
    url: jdbc:h2:file:E:/data/sample
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
springdoc:
  swagger-ui:
    path: /swagger

