spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/auth_service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
#  profiles:
#    active: h2

  mail:
    host: smtp.gmail.com
    port: 587
    username: {username}
    password: {password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

springdoc:
  swagger-ui:
    path: /swagger
    csrf:
      enabled: true
# App properties
app:
  base-uri: http://localhost:8080/
  name: my-blog
  jwt-secret: 413F4428472B4B6250645367566B5970337336763979244226452948404D6351
  #  jwt-expiration-ms: 60000 #1 min
  #  jwt-refresh-expiration-ms: 120000 #2 min
  jwt-expiration-ms: 3600000
  jwt-refresh-expiration-ms: 86400000
  jwt-alg: RSA
  rsa-key-length: 2048
