#server:
#  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/taskhup
    username: root
    password: example_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
#  profiles:
#    active: h2
#logging:
#  level:
#    root: debug
springdoc:
  swagger-ui:
    path: /swagger
    csrf:
      enabled: true
# App properties
app:
  base-uri: http://localhost:8080/
  name: my-blog
  jwt-secret: 413F4428472B4B6250645367566B5970337336763979244226452948404D6351
  #  jwt-expiration-ms: 60000 #1 min
  #  jwt-refresh-expiration-ms: 120000 #2 min
  jwt-expiration-ms: 3600000
  jwt-refresh-expiration-ms: 86400000
  jwt-alg: HS256 #RSA #HS256
  rsa-key-length: 2048
